<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="FB_SlowVentSwitchbox" Id="{ffec64fe-7aa6-0d76-2e1a-f4b9c936a584}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_SlowVentSwitchbox EXTENDS FB_Operation
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_SlowVentSwitchbox">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>