<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.17">
  <POU Name="F_GetTransportTube" Id="{1c225a2d-c668-4975-8e19-7e053353ec27}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_GetTransportTube : REFERENCE TO FB_TransportTube
VAR_INPUT
	eTT : T_TransportTube;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[CASE eTT OF
E_TransportTube.BI1:
	F_GetTransportTube REF= GVL_TransportTubes.fbBI1;
E_TransportTube.BO4:
	F_GetTransportTube REF= GVL_TransportTubes.fbBO4;
ELSE // Invalid transport tube
	F_GetTransportTube REF= 0;
END_CASE]]></ST>
    </Implementation>
    <LineIds Name="F_GetTransportTube">
      <LineId Id="7" Count="0" />
      <LineId Id="9" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="13" Count="1" />
      <LineId Id="21" Count="1" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>